// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project3;

#nullable disable

namespace Project3.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221102104401_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Project3.Bytedata", b =>
                {
                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("byte_image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("ImageId");

                    b.ToTable("Bytedatas");
                });

            modelBuilder.Entity("Project3.Hashkey", b =>
                {
                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("hashkey")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImageId");

                    b.ToTable("Hashkeys");
                });

            modelBuilder.Entity("Project3.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ImageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Project3.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmotionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("res")
                        .HasColumnType("REAL");

                    b.HasKey("ResultId");

                    b.HasIndex("ImageId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Project3.Bytedata", b =>
                {
                    b.HasOne("Project3.Image", "Image")
                        .WithOne("bytedata")
                        .HasForeignKey("Project3.Bytedata", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Project3.Hashkey", b =>
                {
                    b.HasOne("Project3.Image", "Image")
                        .WithOne("hashkey")
                        .HasForeignKey("Project3.Hashkey", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Project3.Result", b =>
                {
                    b.HasOne("Project3.Image", "Image")
                        .WithMany("results")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Project3.Image", b =>
                {
                    b.Navigation("bytedata")
                        .IsRequired();

                    b.Navigation("hashkey")
                        .IsRequired();

                    b.Navigation("results");
                });
#pragma warning restore 612, 618
        }
    }
}
