// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestASP.Models;

#nullable disable

namespace TestASP.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221127110957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("TestASP.Models.Hashcode", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("hashkey")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImageId");

                    b.ToTable("HashCodes");
                });

            modelBuilder.Entity("TestASP.Models.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmotionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("res")
                        .HasColumnType("REAL");

                    b.HasKey("ResultId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("TestASP.Models._Image", b =>
                {
                    b.Property<int>("_ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("byte_image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("_ImageId");

                    b.ToTable("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
